services:
  cotw_trophy_viewer:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: cotw_trophy_viewer
    expose:
      - 8080
    networks:
      - example

networks:
  example:
      name: example_network
      external: true