from enum import Enum, auto


class AnimalType(Enum):
    AMERICAN_ALLIGATOR = auto()
    ANTELOPE_JACKRABBIT = auto()
    AXIS_DEER = auto()
    BANTENG = auto()
    BECEITE_IBEX = auto()
    BIGHORN_SHEEP = auto()
    BLACK_BEAR = auto()
    BLACK_GROUSE = auto()
    BLACKBUCK = auto()
    BLACKTAIL_DEER = auto()
    BLUE_WILDEBEEST = auto()
    BOBWHITE_QUAIL = auto()
    CANADA_GOOSE = auto()
    CAPE_BUFFALO = auto()
    CARIBOU = auto()
    CHAMOIS = auto()
    CINNAMON_TEAL = auto()
    COLLARED_PECCARY = auto()
    COMMON_RACCOON = auto()
    COYOTE = auto()
    EASTERN_COTTONTAIL_RABBIT = auto()
    EASTERN_GREY_KANGAROO = auto()
    EASTERN_WILD_TURKEY = auto()
    BROWN_BEAR = auto()
    EURASIAN_LYNX = auto()
    EURASIAN_TEAL = auto()
    EURASIAN_WIGEON = auto()
    EU_BISON = auto()
    EU_HARE = auto()
    EU_RABBIT = auto()
    FALLOW_DEER = auto()
    FERAL_GOAT = auto()
    FERAL_PIG = auto()
    GEMSBOK = auto()
    GOLDENEYE = auto()
    GREY_FOX = auto()
    GREY_WOLF = auto()
    GREDOS_IBEX = auto()
    GREEN_WINGED_TEAL = auto()
    GREYLAG_GOOSE = auto()
    GRIZZLY_BEAR = auto()
    HARLEQUIN_DUCK = auto()
    HAZEL_GROUSE = auto()
    HOG_DEER = auto()
    IBERIAN_MOUFLON = auto()
    IBERIAN_WOLF = auto()
    JAVAN_RUSA = auto()
    LESSER_KUDU = auto()
    LION = auto()
    MAGPIE_GOOSE = auto()
    MALLARD = auto()
    WILD_TURKEY = auto()
    MEXICAN_BOBCAT = auto()
    MOOSE = auto()
    MOUNTAIN_GOAT = auto()
    MOUNTAIN_HARE = auto()
    MOUNTAIN_LION = auto()
    MULE_DEER = auto()
    PLAINS_BISON = auto()
    PRONGHORN = auto()
    PUMA = auto()
    RACCOON_DOG = auto()
    RED_DEER = auto()
    RED_FOX = auto()
    REINDEER = auto()
    RING_NECKED_PHEASANT = auto()
    RIO_GRANDE_TURKEY = auto()
    ROCK_PTARMIGAN = auto()
    ROCKYMOUNTAIN_ELK = auto()
    ROE_DEER = auto()
    RONDA_IBEX = auto()
    ROOSEVELT_ELK = auto()
    SALTWATER_CROCODILE = auto()
    SAMBAR = auto()
    SCRUB_HARE = auto()
    SIBERIAN_MUSK_DEER = auto()
    SIDE_STRIPED_JACKAL = auto()
    SIKA_DEER = auto()
    SOUTHEASTERN_SPANISH_IBEX = auto()
    SPRINGBOK = auto()
    STUBBLE_QUAIL = auto()
    TUFTED_DUCK = auto()
    TUNDRA_BEAN_GOOSE = auto()
    WARTHOG = auto()
    WATER_BUFFALO = auto()
    WESTERN_CAPERCAILLIE = auto()
    WHITE_TAILED_JACKRABBIT = auto()
    WHITETAIL_DEER = auto()
    WILD_BOAR = auto()
    WILD_HOG = auto()
    WILLOW_PTARMIGAN = auto()
    BOBCAT = auto()
    BLUE_SHEEP = auto()
    WOOLLY_HARE = auto()
    NORTHERN_RED_MUNTJAC = auto()
    TIBETAN_FOX = auto()
    SNOW_LEOPARD = auto()
    TAHR = auto()
    BARASINGHA = auto()
    NILGAI = auto()
    BENGAL_TIGER = auto()
    WILD_YAK = auto()

    def animalName(self) -> str:
        try:
            return _nameMap[self.name]
        except:
            return self.name.replace("_", " ")


_nameMap = {
    "EU_RABBIT": "EUROPEAN RABBIT",
    "WILD_TURKEY": "MERRIAM TURKEY",
    "ROCKYMOUNTAIN_ELK": "ROCKY MOUNTAIN ELK",
}
