from lib.model.animal_type import AnimalType
from lib.model.reserve import Reserve

ANIMALS_RESERVES_CLASSES = {
    Reserve.HIRSCHFELDEN: {
        1: [AnimalType.CANADA_GOOSE, AnimalType.PHEASANT, AnimalType.EU_RABBIT],
        2: [AnimalType.RED_FOX],
        3: [AnimalType.ROE_DEER],
        4: [AnimalType.FALLOW_DEER],
        5: [AnimalType.WILD_BOAR],
        6: [AnimalType.RED_DEER],
        7: [],
        8: [],
        9: [AnimalType.EU_BISON],
    },
    Reserve.LAYTON_LAKE: {
        1: [AnimalType.MALLARD, AnimalType.WILD_TURKEY, AnimalType.JACKRABBIT],
        2: [AnimalType.COYOTE],
        3: [],
        4: [AnimalType.BLACKTAIL_DEER, AnimalType.WHITETAIL_DEER],
        5: [],
        6: [],
        7: [AnimalType.BLACK_BEAR, AnimalType.ROOSEVELT_ELK],
        8: [AnimalType.MOOSE],
        9: [],
    },
    Reserve.MEDVED_TAIGA: {
        1: [AnimalType.WESTERN_CAPERCAILLIE],
        2: [AnimalType.SIBERIAN_MUSK_DEER],
        3: [AnimalType.EURASIAN_LYNX],
        4: [],
        5: [AnimalType.WILD_BOAR],
        6: [AnimalType.GRAY_WOLF, AnimalType.REINDEER],
        7: [AnimalType.EURASIAN_BROWN_BEAR],
        8: [AnimalType.MOOSE],
        9: [],
    },
    Reserve.VURHONGA_SAVANNA: {
        1: [AnimalType.EURASIAN_WIGEON, AnimalType.SCRUB_HARE],
        2: [AnimalType.SIDESTRIPED_JACKAL],
        3: [AnimalType.SPRINGBOK],
        4: [AnimalType.WARTHOG, AnimalType.LESSER_KUDU],
        5: [],
        6: [AnimalType.BLUE_WILDEBEEST, AnimalType.GEMSBOK],
        7: [],
        8: [],
        9: [AnimalType.CAPE_BUFFALO, AnimalType.LION],
    },
    Reserve.PARQUE_FERNANDO: {
        1: [AnimalType.CINNAMON_TEAL],
        2: [],
        3: [AnimalType.BLACKBUCK, AnimalType.AXIS_DEER, AnimalType.COLLARED_PECCARY],
        4: [],
        5: [AnimalType.PUMA, AnimalType.MULE_DEER],
        6: [AnimalType.RED_DEER],
        7: [],
        8: [],
        9: [AnimalType.WATER_BUFFALO],
    },
    Reserve.YUKON_VALLEY: {
        1: [AnimalType.HARLEQUIN_DUCK, AnimalType.CANADA_GOOSE],
        2: [AnimalType.RED_FOX],
        3: [],
        4: [],
        5: [AnimalType.GRAY_WOLF, AnimalType.CARIBOU],
        6: [],
        7: [],
        8: [AnimalType.MOOSE, AnimalType.GRIZZLY_BEAR],
        9: [AnimalType.PLAINS_BISON],
    },
    Reserve.CUATRO_COLINAS: {
        1: [AnimalType.PHEASANT, AnimalType.EU_HARE],
        2: [],
        3: [AnimalType.ROE_DEER],
        4: [AnimalType.IBERIAN_MOUFLON, AnimalType.RONDA_IBEX, AnimalType.BECEITE_IBEX, AnimalType.GREDOS_IBEX,
            AnimalType.SOUTHEASTERN_IBEX],
        5: [AnimalType.WILD_BOAR],
        6: [AnimalType.IBERIAN_WOLF, AnimalType.RED_DEER],
        7: [],
        8: [],
        9: [],
    },
    Reserve.SILVER_RIDGE_PEAKS: {
        1: [AnimalType.WILD_TURKEY],
        2: [],
        3: [AnimalType.PRONG_HORN],
        4: [AnimalType.MOUNTAIN_GOAT],
        5: [AnimalType.BIGHORN_SHEEP, AnimalType.PUMA, AnimalType.MULE_DEER],
        6: [],
        7: [AnimalType.BLACK_BEAR, AnimalType.ROCKYMOUNTAIN_ELK],
        8: [],
        9: [AnimalType.PLAINS_BISON],
    },
    Reserve.TE_AWAROA_NATIONAL_PARK: {
        1: [AnimalType.WILD_TURKEY, AnimalType.MALLARD, AnimalType.EU_RABBIT],
        2: [],
        3: [AnimalType.CHAMOIS, AnimalType.FERAL_GOAT],
        4: [AnimalType.SIKA_DEER, AnimalType.FALLOW_DEER, AnimalType.TAHR],
        5: [AnimalType.FERAL_PIG],
        6: [AnimalType.RED_DEER],
        7: [],
        8: [],
        9: [],
    },
    Reserve.RANCHO_DEL_ARROYO: {
        1: [AnimalType.RIO_GRANDE_TURKEY, AnimalType.PHEASANT, AnimalType.ANTELOPE_JACKRABBIT],
        2: [AnimalType.COYOTE, AnimalType.MEXICAN_BOBCAT],
        3: [AnimalType.COLLARED_PECCARY, AnimalType.PRONG_HORN],
        4: [AnimalType.WHITETAIL_DEER],
        5: [AnimalType.MULE_DEER, AnimalType.BIGHORN_SHEEP],
        6: [],
        7: [],
        8: [],
        9: [],
    },
    Reserve.MISSISSIPPI_ACRES_PRESERVE: {
        1: [AnimalType.NORTHERN_BOBWHITE_QUAIL, AnimalType.EASTERN_WILD_TURKEY, AnimalType.GREEN_WING_TEAL,
            AnimalType.EASTERN_COTTONTAIL_RABBIT],
        2: [AnimalType.GRAY_FOX, AnimalType.RACCOON],
        3: [],
        4: [AnimalType.WHITETAIL_DEER],
        5: [AnimalType.FERAL_PIG],
        6: [AnimalType.AMERICAN_ALLIGATOR, AnimalType.BLACK_BEAR],
        7: [],
        8: [],
        9: [],
    },
    Reserve.REVONTULI_COAST: {
        1: [AnimalType.EURASIAN_WIGEON, AnimalType.EURASIAN_TEAL, AnimalType.GOLDENEYE, AnimalType.MALLARD,
            AnimalType.TUFTED_DUCK, AnimalType.CANADA_GOOSE,
            AnimalType.GREYLAG_GOOSE, AnimalType.TUNDRA_BEAN_GOOSE, AnimalType.BLACK_GROUSE, AnimalType.HAZEL_GROUSE,
            AnimalType.WESTERN_CAPERCAILLIE,
            AnimalType.ROCK_PTARMIGAN, AnimalType.WILLOW_PTARMIGAN, AnimalType.MOUNTAIN_HARE],
        2: [AnimalType.RACCOON_DOG],
        3: [AnimalType.EURASIAN_LYNX],
        4: [AnimalType.WHITETAIL_DEER],
        5: [],
        6: [],
        7: [AnimalType.EURASIAN_BROWN_BEAR],
        8: [AnimalType.MOOSE],
        9: [],
    },
    Reserve.NEW_ENGLAND_MOUNTAINS: {
        1: [AnimalType.PHEASANT, AnimalType.NORTHERN_BOBWHITE_QUAIL, AnimalType.EASTERN_WILD_TURKEY,
            AnimalType.GOLDENEYE, AnimalType.MALLARD,
            AnimalType.GREEN_WING_TEAL, AnimalType.EASTERN_COTTONTAIL_RABBIT],
        2: [AnimalType.RED_FOX, AnimalType.GRAY_FOX, AnimalType.COYOTE, AnimalType.RACCOON, AnimalType.BOBCAT],
        3: [],
        4: [AnimalType.WHITETAIL_DEER],
        5: [],
        6: [],
        7: [AnimalType.BLACK_BEAR],
        8: [AnimalType.MOOSE],
        9: [],
    },
    Reserve.SUNDARPATAN: {
        1: [AnimalType.GREYLAG_GOOSE, AnimalType.WOOLLY_HARE],
        2: [AnimalType.NORTHERN_RED_MUNTJAC, AnimalType.TIBETAN_FOX],
        3: [AnimalType.BLACKBUCK],
        4: [AnimalType.SNOW_LEOPARD, AnimalType.BLUE_SHEEP, AnimalType.TAHR],
        5: [],
        6: [AnimalType.BARASINGHA, AnimalType.NILGAI],
        7: [],
        8: [],
        9: [AnimalType.BENGAL_TIGER, AnimalType.WATER_BUFFALO, AnimalType.WILD_YAK],
    },
    Reserve.EMERALD_COAST: {
        1: [AnimalType.MAGPIE_GOOSE, AnimalType.STUBBLE_QUAIL],
        2: [AnimalType.RED_FOX],
        3: [AnimalType.HOG_DEER, AnimalType.AXIS_DEER, AnimalType.FERAL_GOAT],
        4: [AnimalType.EASTERN_GREY_KANGAROO, AnimalType.FALLOW_DEER],
        5: [AnimalType.FERAL_PIG, AnimalType.JAVAN_RUSA],
        6: [AnimalType.RED_DEER],
        7: [AnimalType.SAMBAR],
        8: [AnimalType.SALTWATER_CROCODILE],
        9: [AnimalType.BANTENG],
    },
    Reserve.SALZWIESEN_PARK: {
        1: [AnimalType.BLACK_GROUSE, AnimalType.EURASIAN_TEAL, AnimalType.EURASIAN_WIGEON, AnimalType.EU_RABBIT,
            AnimalType.FERRUGINOUS_DUCK, AnimalType.GADWALL, AnimalType.GOLDENEYE, AnimalType.GREYLAG_GOOSE,
            AnimalType.MALLARD, AnimalType.PHEASANT, AnimalType.TUFTED_DUCK, AnimalType.TUNDRA_BEAN_GOOSE],
        2: [AnimalType.RACCOON, AnimalType.RACCOON_DOG, AnimalType.RED_FOX],
        3: [],
        4: [],
        5: [],
        6: [],
        7: [],
        8: [],
        9: [],
    },
    Reserve.ASKIY_RIDGE: {
        1: [AnimalType.DUSKY_GROUSE, AnimalType.NORTHERN_PINTAIL, AnimalType.WOOD_DUCK, AnimalType.SNOW_GOOSE,
            AnimalType.CANADA_GOOSE, AnimalType.MALLARD, AnimalType.PHEASANT],
        2: [AnimalType.NORTH_AMERICAN_BEAVER],
        3: [AnimalType.PRONG_HORN],
        4: [AnimalType.WHITETAIL_DEER, AnimalType.MOUNTAIN_GOAT],
        5: [AnimalType.BIGHORN_SHEEP, AnimalType.MULE_DEER],
        6: [AnimalType.GRAY_WOLF, AnimalType.WOODLAND_CARIBOU],
        7: [AnimalType.BLACK_BEAR, AnimalType.MANITOBAN_ELK],
        8: [AnimalType.MOOSE],
        9: [AnimalType.WOOD_BISON],
    },
}
