from lib.model.animalType import AnimalType
from lib.model.reserve import Reserve

RESERVES_ANIMALS_CLASSES = {
    Reserve.HIRSCHFELDEN: {
        1: [AnimalType.CANADA_GOOSE, AnimalType.RING_NECKED_PHEASANT, AnimalType.EU_RABBIT],
        2: [AnimalType.RED_FOX],
        3: [AnimalType.ROE_DEER],
        4: [AnimalType.FALLOW_DEER, AnimalType.WILD_BOAR],
        5: [],
        6: [AnimalType.RED_DEER],
        7: [],
        8: [],
        9: [AnimalType.EU_BISON],
    },
    Reserve.LAYTON_LAKE: {
        1: [AnimalType.MALLARD, AnimalType.WILD_TURKEY, AnimalType.WHITE_TAILED_JACKRABBIT],
        2: [AnimalType.COYOTE],
        3: [],
        4: [AnimalType.BLACKTAIL_DEER, AnimalType.WHITETAIL_DEER],
        5: [],
        6: [],
        7: [AnimalType.BLACK_BEAR],
        8: [AnimalType.ROOSEVELT_ELK, AnimalType.MOOSE],
        9: [],
    },
    Reserve.MEDVED_TAIGA: {
        1: [AnimalType.WESTERN_CAPERCAILLIE],
        2: [AnimalType.SIBERIAN_MUSK_DEER],
        3: [AnimalType.EURASIAN_LYNX],
        4: [AnimalType.WILD_BOAR],
        5: [AnimalType.GREY_WOLF],
        6: [AnimalType.REINDEER],
        7: [AnimalType.BROWN_BEAR],
        8: [AnimalType.MOOSE],
        9: [],
    },
    Reserve.VURHONGA_SAVANNA: {
        1: [AnimalType.EURASIAN_WIGEON, AnimalType.SCRUB_HARE],
        2: [AnimalType.SIDE_STRIPED_JACKAL],
        3: [AnimalType.SPRINGBOK],
        4: [AnimalType.WARTHOG, AnimalType.LESSER_KUDU],
        5: [],
        6: [AnimalType.BLUE_WILDEBEEST],
        7: [],
        8: [AnimalType.GEMSBOK],
        9: [AnimalType.CAPE_BUFFALO, AnimalType.LION],
    },
    Reserve.PARQUE_FERNANDO: {
        1: [AnimalType.CINNAMON_TEAL],
        2: [],
        3: [AnimalType.BLACKBUCK, AnimalType.AXIS_DEER],
        4: [AnimalType.COLLARED_PECCARY],
        5: [AnimalType.PUMA],
        6: [AnimalType.MULE_DEER, AnimalType.RED_DEER],
        7: [],
        8: [],
        9: [AnimalType.WATER_BUFFALO],
    },
    Reserve.YUKON_VALLEY: {
        1: [AnimalType.HARLEQUIN_DUCK, AnimalType.CANADA_GOOSE],
        2: [AnimalType.RED_FOX],
        3: [],
        4: [],
        5: [AnimalType.GREY_WOLF],
        6: [AnimalType.CARIBOU],
        7: [AnimalType.GRIZZLY_BEAR],
        8: [AnimalType.MOOSE],
        9: [AnimalType.PLAINS_BISON],
    },
    Reserve.CUATRO_COLINAS: {
        1: [AnimalType.RING_NECKED_PHEASANT, AnimalType.EU_HARE],
        2: [],
        3: [AnimalType.ROE_DEER],
        4: [AnimalType.IBERIAN_MOUFLON, AnimalType.RONDA_IBEX, AnimalType.BECEITE_IBEX, AnimalType.GREDOS_IBEX, AnimalType.SOUTHEASTERN_SPANISH_IBEX,
            AnimalType.WILD_BOAR],
        5: [AnimalType.IBERIAN_WOLF],
        6: [AnimalType.RED_DEER],
        7: [],
        8: [],
        9: [],
    },
    Reserve.SILVER_RIDGE_PEAKS: {
        1: [AnimalType.WILD_TURKEY],
        2: [],
        3: [],
        4: [AnimalType.PRONGHORN, AnimalType.MOUNTAIN_GOAT, AnimalType.BIGHORN_SHEEP],
        5: [AnimalType.MOUNTAIN_LION],
        6: [AnimalType.MULE_DEER],
        7: [AnimalType.BLACK_BEAR],
        8: [AnimalType.ROCKYMOUNTAIN_ELK],
        9: [AnimalType.PLAINS_BISON],
    },
    Reserve.TE_AWAROA_NATIONAL_PARK: {
        1: [AnimalType.WILD_TURKEY, AnimalType.MALLARD, AnimalType.EU_RABBIT],
        2: [],
        3: [AnimalType.CHAMOIS, AnimalType.FERAL_GOAT],
        4: [AnimalType.SIKA_DEER, AnimalType.FALLOW_DEER, AnimalType.FERAL_PIG],
        5: [],
        6: [AnimalType.RED_DEER],
        7: [],
        8: [],
        9: [],
    },
    Reserve.RANCHO_DEL_ARROYO: {
        1: [AnimalType.RIO_GRANDE_TURKEY, AnimalType.RING_NECKED_PHEASANT, AnimalType.ANTELOPE_JACKRABBIT],
        2: [AnimalType.COYOTE],
        3: [AnimalType.MEXICAN_BOBCAT],
        4: [AnimalType.COLLARED_PECCARY, AnimalType.BIGHORN_SHEEP, AnimalType.WHITETAIL_DEER, AnimalType.PRONGHORN],
        5: [],
        6: [AnimalType.MULE_DEER],
        7: [],
        8: [],
        9: [],
    },
    Reserve.MISSISSIPPI_ACRES_PRESERVE: {
        1: [AnimalType.BOBWHITE_QUAIL, AnimalType.EASTERN_WILD_TURKEY, AnimalType.GREEN_WINGED_TEAL, AnimalType.EASTERN_COTTONTAIL_RABBIT],
        2: [AnimalType.GREY_FOX, AnimalType.COMMON_RACCOON],
        3: [],
        4: [AnimalType.WHITETAIL_DEER, AnimalType.WILD_HOG],
        5: [],
        6: [AnimalType.AMERICAN_ALLIGATOR],
        7: [AnimalType.BLACK_BEAR],
        8: [],
        9: [],
    },
    Reserve.REVONTULI_COAST: {
        1: [AnimalType.EURASIAN_WIGEON, AnimalType.EURASIAN_TEAL, AnimalType.GOLDENEYE, AnimalType.MALLARD, AnimalType.TUFTED_DUCK, AnimalType.CANADA_GOOSE,
            AnimalType.GREYLAG_GOOSE, AnimalType.TUNDRA_BEAN_GOOSE, AnimalType.BLACK_GROUSE, AnimalType.HAZEL_GROUSE, AnimalType.WESTERN_CAPERCAILLIE,
            AnimalType.ROCK_PTARMIGAN, AnimalType.WILLOW_PTARMIGAN, AnimalType.MOUNTAIN_HARE],
        2: [AnimalType.RACCOON_DOG],
        3: [AnimalType.EURASIAN_LYNX],
        4: [AnimalType.WHITETAIL_DEER],
        5: [],
        6: [],
        7: [AnimalType.BROWN_BEAR],
        8: [AnimalType.MOOSE],
        9: [],
    },
    Reserve.NEW_ENGLAND_MOUNTAINS: {
        1: [AnimalType.RING_NECKED_PHEASANT, AnimalType.BOBWHITE_QUAIL, AnimalType.EASTERN_WILD_TURKEY, AnimalType.GOLDENEYE, AnimalType.MALLARD,
            AnimalType.GREEN_WINGED_TEAL, AnimalType.EASTERN_COTTONTAIL_RABBIT],
        2: [AnimalType.RED_FOX, AnimalType.GREY_FOX, AnimalType.COYOTE, AnimalType.COMMON_RACCOON],
        3: [AnimalType.BOBCAT],
        4: [AnimalType.WHITETAIL_DEER],
        5: [],
        6: [],
        7: [AnimalType.BLACK_BEAR],
        8: [AnimalType.MOOSE],
        9: [],
    },
    Reserve.SUNDARPATAN: {
        1: [AnimalType.GREYLAG_GOOSE, AnimalType.WOOLLY_HARE],
        2: [AnimalType.NORTHERN_RED_MUNTJAC, AnimalType.TIBETAN_FOX],
        3: [AnimalType.BLACKBUCK],
        4: [AnimalType.SNOW_LEOPARD, AnimalType.BLUE_SHEEP, AnimalType.TAHR],
        5: [],
        6: [AnimalType.BARASINGHA, AnimalType.NILGAI],
        7: [],
        8: [],
        9: [AnimalType.BENGAL_TIGER, AnimalType.WATER_BUFFALO, AnimalType.WILD_YAK],
    },
    Reserve.EMERALD_COAST: {
        1: [AnimalType.MAGPIE_GOOSE, AnimalType.STUBBLE_QUAIL],
        2: [AnimalType.RED_FOX],
        3: [AnimalType.HOG_DEER, AnimalType.AXIS_DEER, AnimalType.FERAL_GOAT],
        4: [AnimalType.EASTERN_GREY_KANGAROO, AnimalType.FALLOW_DEER, AnimalType.FERAL_PIG],
        5: [],
        6: [AnimalType.RED_DEER, AnimalType.SAMBAR, AnimalType.JAVAN_RUSA],
        7: [AnimalType.SALTWATER_CROCODILE],
        8: [],
        9: [AnimalType.BANTENG],
    },
}

GENDERS = {
    0: "FEMALE",
    1: "MALE"
}

DIFFICULTY_SCORE_THRESHOLDS = [0, 0.115, 0.225, 0.335, 0.445, 0.555, 0.665, 0.775, 0.885]

DIFFICULTIES = {
    0: "TRIVIAL",
    1: "MINOR",
    2: "VERY EASY",
    3: "EASY",
    4: "MEDIUM",
    5: "HARD",
    6: "VERY HARD",
    7: "MYTHICAL",
    8: "LEGENDARY",
    9: "FABLED",
}

def getKeyFor(constant, label) -> int:
    return next(key for key, labels in constant.items() if labels == label)
